// Generated by TKG at 2021-11-22 06:30:00

#include "keymap.h"

#define KEYMAP_TKG( \
    K0A, K0B, K0C, K0D, K0E  \
) { \
    { KC_##K0A, KC_##K0B, KC_##K0C, KC_##K0D, KC_##K0E }  \
}

#ifdef KEYMAP_SECTION_ENABLE
const uint16_t keymaps[][MATRIX_ROWS][MATRIX_COLS] __attribute__ ((section (".keymap.keymaps"))) = {
#else
const uint16_t keymaps[][MATRIX_ROWS][MATRIX_COLS] PROGMEM = {
#endif
    [0] = KEYMAP_TKG(
        UP,  FN1, RGHT,DOWN,LEFT),
    [1] = KEYMAP_TKG(
        FN2, FN1, FN5, FN4, FN3),
};
};
#ifdef KEYMAP_SECTION_ENABLE
const uint16_t fn_actions[] __attribute__ ((section (".keymap.fn_actions"))) = {
#else
const uint16_t fn_actions[] PROGMEM = {
#endif
    [1] = ACTION_LAYER_TAP_KEY(1, KC_DELETE),
    [2] = ACTION_BACKLIGHT_INCREASE(),
    [3] = ACTION_FUNCTION(),
    [4] = ACTION_BACKLIGHT_DECREASE(),
    [5] = ACTION_FUNCTION(3, ),
};
};
